config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users, only: [:show, :edit] do
      resources :events, only: [:index, :show] do
        patch :accept, to: 'events#accept'
        delete :refuse, to: 'events#refuse'
      end
      resources :plans
      resources :plans, only: [:show] do
        resources :events, only: [:index, :new, :create, :edit, :update, :destroy]
      end      
    end
  end
  devise_for :users
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy'
    get 'signin', to: 'devise/sessions#new'
    post 'signin', to: 'devise/sessions#create'
    get 'signup', to: 'devise/registration#new'
  end
  root to: 'users#index'
  resources :users, only: [:show] do
    resources :events, only: [:index, :show] do
      resources :chats, only: [:index, :create]
    end
    resources :plans, only: [:show, :create, :edit, :update] do
      resources :events, only: [:index]
      patch 'events', to: 'events#reserve'
    end
  end

end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :plan
    has_many :chats
    enum status: { not_offerred: 0, accepted: 1 }

    def participant
        User.find_by(id: self.participant_id)
    end

    def organizer
        User.find_by(id: self.organizer_id)
    end

    def over?
        self.scheduled_datetime < Time.now
    end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  def new
    @event = Event.new
    @time = Time.now
    @plan = current_user.plans.find(params[:plan_id])
  end

  def create
    plan = current_user.plans.find(params[:plan_id])
    @time = create_datetime(datetime_params)
    event = plan.events.new(scheduled_datetime: @time, organizer_id: current_user.id)
    if event.save
      redirect_to admin_user_plan_path(current_user, plan), notice: 'Success'
    else
      flash.now[:alert] = event.errors.full_messages
      render 'new'
    end
  end

  def index
    @events = Event.where(organizer_id: current_user.id)
  end


  def accept
    event = Event.find(params[:event_id])
    event.accepted!
    redirect_to request.referrer, notice: 'accepted event'
  end

  def refuse
    event = Event.find(params[:event_id])
    event.not_offerred!
    redirect_to request.referrer, notice: 'refused event'
  end

  private

    def datetime_params
      params.require(:event).permit(:year, :month, :day, :hour,:minute)
    end

    def create_datetime(params)
      time_data = [params[:year], params[:month], params[:day], params[:hour], params[:minute], 0]
      Time.zone.local(*time_data)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def reserve
    event = Event.find_by(event_params)
    event.participant_id = current_user.id
    if event.save
      redirect_to user_events_path(current_user), notice: 'Success Reservation'
    else
      falsh.now[:alert] = event.errors.full_messages
      render request.referer
    end
  end

  def index
    @events = Event.where(participant_id: current_user.id)
  end

  def show
  end

  private
  def event_params
    params.require(:event).permit(:id)
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/create.html.erb
<h1>Admin::Events#create</h1>
<p>Find me in app/views/admin/events/create.html.erb</p>

app/views/admin/events/edit.html.erb
<h1>Admin::Events#edit</h1>
<p>Find me in app/views/admin/events/edit.html.erb</p>

app/views/admin/events/index.html.erb
<h1 class="title">My Reserved Events</h1>
<p>Find me in app/views/admin/events/edit.html.erb</p>
<% @events.each do |event| %>
    <% if event.participant_id %>
        <li class=<%= event.over? ? "past" : "" %>>
            <%= event.scheduled_datetime %> (<%= event.status %>)| 
            <%= event.participant&.name %> | 
            <%= link_to '承認', admin_user_event_accept_path(event.participant_id, event.id), method: :patch, data: { confirm: 'Are you sure?' } %> | 
            <%= link_to '拒否', admin_user_event_refuse_path(event.participant_id, event.id), method: :delete, data: { confirm: 'Are you sure?' }  %>
        </li>
    <% end %>
<% end %>

app/views/admin/events/new.html.erb
<h1>Admin::Events#new</h1>
<p>Find me in app/views/admin/events/edit.html.erb</p>
<%= form_with model: @event, scope: :event, url: admin_user_plan_events_path(current_user, @plan), method: :POST do |f| %>
    <div class="field">
        <%= f.label '日付：' %>
        <%= f.select :year, (@time.year..@time.since(10.years).year).to_a, { selected: Time.now.year } %>
        <%= f.select :month, (1..12).to_a, { selected: Time.now.month } %>
        <%= f.select :day, (1..31).to_a, { selected: Time.now.day } %>　
        <%= f.label '時刻：' %>
        <%= f.select :hour, (8..24).to_a, { selected: Time.now.hour } %>：
        <%= f.select :minute, [0, 15, 30, 45] %>
    </div>
    <div class="field">
        <%= f.submit '新規作成' %>
    </div>
<% end %>

app/views/admin/events/show.html.erb
<h1>Admin::Events#show</h1>
<p>Find me in app/views/admin/events/show.html.erb</p>

app/views/admin/events/update.html.erb
<h1>Admin::Events#update</h1>
<p>Find me in app/views/admin/events/update.html.erb</p>