config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users, only: [:show, :edit] do
      resources :events, only: [:index, :show] do
        patch :accept, to: 'events#accept'
        delete :refuse, to: 'events#refuse'
      end
      resources :plans
      resources :plans, only: [:show] do
        resources :events, only: [:index, :new, :create, :edit, :update, :destroy]
      end      
    end
  end
  devise_for :users
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy'
    get 'signin', to: 'devise/sessions#new'
    post 'signin', to: 'devise/sessions#create'
    get 'signup', to: 'devise/registration#new'
  end
  root to: 'users#index'
  resources :users, only: [:show] do
    resources :events, only: [:index, :show] do
      resources :chats, only: [:index, :create]
    end
    resources :plans, only: [:show, :create, :edit, :update] do
      resources :events, only: [:index]
      patch 'events', to: 'events#reserve'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :event

    def sender
        User.find_by_id(self.sender_id)
    end
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :plan
    has_many :chats
    enum status: { not_offerred: 0, accepted: 1 }

    def participant
        User.find_by(id: self.participant_id)
    end

    def organizer
        User.find_by(id: self.organizer_id)
    end

    def over?
        self.scheduled_datetime < Time.now
    end
end

app/models/plan.rb
class Plan < ApplicationRecord
    belongs_to :user
    has_many :events

    validates :plan_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :plans
end

app/controllers/admin/plans_controller.rb
class Admin::PlansController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery :except => [:create]

  def show
    @user = User.find(params[:user_id])
    @plan = @user.plans.find(params[:id])
    if @user != current_user
      redirect_to user_plan_path(@user, @plan)
    end
  end

  def new
    @plan = current_user.plans.new
  end

  def create
    plan = current_user.plans.new(plan_params)
    if plan.save
      redirect_to admin_user_path(current_user), notice: 'Success!'
    else
      flash.now[:alert] = "Failed to create new"
      render new_admin_plan_path
    end
  end

  def edit
    @plan = current_user.plans.find(params[:id])
  end

  def update
    @plan = current_user.plans.find(params[:id])
    if @plan.update(plan_params)
      redirect_to admin_user_plan_path(current_user, @plan), notice: 'Success!'
    else
      flash.now[:alert] = @plan.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    plan = Plan.find(params[:id])
    if plan.destroy
      redirect_to admin_user_plan_path(current_user, plan), notice: 'Success to delete!'
    else
      flash.now[:alert] = 'Failed to delete'
      render request.referer
    end
  end

  private
    def plan_params
      params.require(:plan).permit(:plan_name, :description, :user_id)
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :get_event

  def index
    @event = Event.find_by(id: params[:event_id])
    @chat = @event.chats.new
  end

  def create
    chat = Chat.new(content: chat_params[:content], event_id: @event.id, sender_id: current_user.id, receiver_id: @event.organizer_id)
    if chat.save
      redirect_to request.referrer, notice: 'Success'
    else
      flash.now[:alert] = "Submit failed"
      render 'index'
    end

  end

  private
    def chat_params
      params.require(:chat).permit(:content)
    end

    def get_event
      @event = Event.find_by(id: params[:event_id])
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def reserve
    event = Event.find_by(event_params)
    event.participant_id = current_user.id
    if event.save
      redirect_to user_events_path(current_user), notice: 'Success Reservation'
    else
      falsh.now[:alert] = event.errors.full_messages
      render request.referer
    end
  end

  def index
    @events = Event.where(participant_id: current_user.id)
  end

  def show
  end

  private
  def event_params
    params.require(:event).permit(:id)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
    @user = User.find_by(params[:user_id])
    @plan = Plan.find(params[:id])
    if @user == current_user
      redirect_to admin_user_plan_path(@user, @plan)
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where.not(id: current_user)
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user
      redirect_to admin_user_path(current_user)
    else

    end
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/plans_helper.rb
module Admin::PlansHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_head.html.erb
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    <%= favicon_link_tag('favicon.ico') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReserverChat</title>
    <%= render "layouts/head"%>
  </head>

  <body>
      <%= render 'shared/errors' %>
      <%= render 'shared/header' %>
      <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

app/views/shared/_header.html.erb
    <nav class="navbar">
      <div class="navbar-brand">
        <%= image_tag "calendar-icon.png", size: "50x20", class: "logo" %>
      </div>

      <div class="navbar-menu is-active">
        <div class="navbar-start">
          <%= link_to '一覧', root_path, class:"navbar-item" %>
          <% if user_signed_in? %>
            <%= link_to "#{current_user.name} (プラン一覧）", admin_user_path(current_user), class:"navbar-item" %>
            <%= link_to 'My Reserved Events', admin_user_events_path(current_user), class:"navbar-item" %>
            <%= link_to 'My Applied Reservations', user_events_path(current_user), class:"navbar-item" %>
            <div class="navbar-end">
              <%= link_to 'log out', logout_path, method: :delete, class:"navbar-item logout button" %>
            </div>
          <% else %>
            <div class="navbar-end">
              <%= link_to 'sign in', signin_path, class:"navbar-item button is-lighter" %>
            </div>
          <% end %>
        </div>
      </div>
    </nav>