config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users, only: [:show, :edit] do
      resources :events, only: [:index, :show] do
        patch :accept, to: 'events#accept'
        delete :refuse, to: 'events#refuse'
      end
      resources :plans
      resources :plans, only: [:show] do
        resources :events, only: [:index, :new, :create, :edit, :update, :destroy]
      end      
    end
  end
  devise_for :users
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy'
    get 'signin', to: 'devise/sessions#new'
    post 'signin', to: 'devise/sessions#create'
    get 'signup', to: 'devise/registration#new'
  end
  root to: 'users#index'
  resources :users, only: [:show] do
    resources :events, only: [:index, :show] do
      resources :chats, only: [:index, :create]
    end
    resources :plans, only: [:show, :create, :edit, :update] do
      resources :events, only: [:index]
      patch 'events', to: 'events#reserve'
    end
  end

end

app/models/plan.rb
class Plan < ApplicationRecord
    belongs_to :user
    has_many :events

    validates :plan_name, presence: true
end

app/controllers/admin/plans_controller.rb
class Admin::PlansController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery :except => [:create]

  def show
    @user = User.find(params[:user_id])
    @plan = @user.plans.find(params[:id])
    if @user != current_user
      redirect_to user_plan_path(@user, @plan)
    end
  end

  def new
    @plan = current_user.plans.new
  end

  def create
    plan = current_user.plans.new(plan_params)
    if plan.save
      redirect_to admin_user_path(current_user), notice: 'Success!'
    else
      flash.now[:alert] = "Failed to create new"
      render new_admin_plan_path
    end
  end

  def edit
    @plan = current_user.plans.find(params[:id])
  end

  def update
    @plan = current_user.plans.find(params[:id])
    if @plan.update(plan_params)
      redirect_to admin_user_plan_path(current_user, @plan), notice: 'Success!'
    else
      flash.now[:alert] = @plan.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    plan = Plan.find(params[:id])
    if plan.destroy
      redirect_to admin_user_plan_path(current_user, plan), notice: 'Success to delete!'
    else
      flash.now[:alert] = 'Failed to delete'
      render request.referer
    end
  end

  private
    def plan_params
      params.require(:plan).permit(:plan_name, :description, :user_id)
    end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
    @user = User.find_by(params[:user_id])
    @plan = Plan.find(params[:id])
    if @user == current_user
      redirect_to admin_user_plan_path(@user, @plan)
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/admin/plans_helper.rb
module Admin::PlansHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/edit.html.erb
<h1>Plans#edit</h1>
<p>Find me in app/views/plans/edit.html.erb</p>

app/views/plans/index.html.erb
<h1>Plans#index</h1>
<p>Find me in app/views/plans/index.html.erb</p>

app/views/plans/new.html.erb
<h1>Plans#new</h1>
<p>Find me in app/views/plans/new.html.erb</p>

app/views/plans/show.html.erb
<h1>Plans#show</h1>
<p>Find me in app/views/plans/show.html.erb</p>
<h2><strong>plan name: </strong><%= @plan.plan_name %></h2>
<p><strong>description: </strong><%= @plan.description %></p>
<br/>
<% if user_signed_in? %>
    <h3>予約可能日程一覧</h3>
    <%= form_with model: @plan.events.new, url: user_plan_events_path(@user, @plan), 
            method: :patch do |f| %>
        <ul>
            <% @plan.events.each do |event| %>
                <li>
                    <label>
                        <%= f.radio_button :id, event.id %>
                        <%= event.scheduled_datetime %>
                    </label>
                </li>
            <% end %>
        </ul>
        <%= f.submit "Reserve", {class: "button is-link"} %>
    <% end %>
<% end %>